### ISSUE TITLE
Responsiveness issue in sr_listings_slider

### ISSUE THREAD

**Issue by CodyReichert** [SimplyRETS/simplyretswp#10]
### `[sr_listings_slider]`

The markup generated by this short-code breaks on (small) mobile devices. Medium and large screens are OK

**Comment by creichert** [comment]
Is the theme or plugin actually responsive?

**Comment by CodyReichert** [comment]
They both should be

**Comment by CodyReichert** [comment]
There's no issue here - the problem is on the user's site.
