### ISSUE TITLE
Extracting postal codes covered by a MLS vendor

### ISSUE THREAD

**Issue by jameshaggard** [SimplyRETS/simplyretswp#104]
Is it possible to get a list of postal codes covered by TREB? I don't think you return postal/zip codes in the options call for a rets feed.

**Comment by creichert** [comment]
There are a significant number of distinct postal codes. What do you
need them for? We may be able to provide a static list of them, but I
doubt they can be used on a website in a big drop-down.

**Comment by jameshaggard** [comment]
A client asked for it but didn't say what they needed it for. Should I give them the option of providing a static list?

**Comment by CodyReichert** [comment]
@james - this needs to be in the main SimplyRETS repo, can you re-open in there?
