### ISSUE TITLE
[Story] Add OpenHouses support

### ISSUE THREAD

**Issue by CodyReichert** [SimplyRETS/simplyretswp#111]
The plugin doesn't currently supporting the SimplyRETS OpenHouses API. We can/should add support for these so that more people can use OpenHouses via the plugin.

A couple of thoughts:
1. We could probably have a completely separate short-code, `[sr_openhouses]` that works just like `[sr_listings]`.
2. You could also have an option that checks for open houses on all listing details pages -- that way you could show any open house times at the top of the page.

It would be harder to show Open House times within the `[sr_listings]` search results, because you would need to make a request for each house in the results list to check for an open house -- so this method likely isn't do-able. But having the two things mentioned above would go a long ways towards supporting the Enterprise plan in the plugin.

**Comment by CodyReichert** [comment]
> You could also have an option that checks for open houses on all listing details pages -- that way you could show any open house times at the top of the page.

Just following up here: this one specifically would be pretty trivial.

If a user has `EnterpriseAccess`, we can call `/openhouses` on the listing details pages and show open house information if it exists.

**Comment by southbaydigs** [comment]
We would love to see this feature included.

**Comment by CodyReichert** [comment]
@southbaydigs - Thank you for the feedback! This is one we've wanted to add for a while now. I'll see if we can get it queued on our roadmap for the next week or two :tada:

**Comment by CodyReichert** [comment]
@southbaydigs - Wanted to ping you to let you know that open houses are now available in the WordPress plugin! We're working on adding some documentation to the [plugin website](http://wordpress-demo.simplyrets.com), but a few initial notes:

- If you're on the Enterprise plan, the plugin will automatically check for open houses when loading a single listing details page. You don't have to do anything additional for this to work.
- There's a new `[sr_openhouses]` short-code you can use to show a list of open houses. This short-code takes different filters (for example: `[sr_openhouses cities="San Francisco"]` [listed in the API docs here](https://docs.simplyrets.com/api/index.html#!/default/get_openhouses). (We'll add wordpress specific docs for this soon).

Just make sure, if you're using the plugin, that you're updated to at least v2.8.2. We have a few other features coming up here too (#150).

Thank you!
