### ISSUE TITLE
Invalid html attributes on advanced search form

### ISSUE THREAD

**Issue by spmiller2** [SimplyRETS/simplyretswp#121]
2. On the search form, when display `advanced="true"` is enabled and the advanced search form is displayed, the CSS for beds and baths doesn't have labels so those fields can be hidden.

The label for `Bedrooms` seems to be one used for other attributes
<label for="sr-adv-minprice"><strong>Bedrooms</strong></label>

And` Bathrooms` seems to be missing a label.
 <label><strong>Bathrooms</strong></label>

**Comment by CodyReichert** [comment]
Fixed in #122
