### ISSUE TITLE
Support multiple values on [sr_listings_slider]

### ISSUE THREAD

**Issue by spmiller2** [SimplyRETS/simplyretswp#127]
[sr_listings_slider] currently only takes one value in the attributes

Works [sr_listings_slider q="201901619"]
Does not work [sr_listings_slider q="201901619; 201901679; 201900722; 201901677"]

When you want finite control over what is displayed, being able to specify more than one parameter would be helpful - say use case "I want to feature only these 10 specific properties in the slider" or " I want listings from these two cities to appear"

**Comment by CodyReichert** [comment]
This one is fixed up since (at least) v2.8.8, I believe.

Uses the same logic as `[sr_listings]` to parse the parameters, so the behavior is the same between the two.
