### ISSUE TITLE
"SignedInNotSupported" by Google Maps API

### ISSUE THREAD

**Issue by spmiller2** [SimplyRETS/simplyretswp#138]
I noticed while reviewing developer tools when loading the map in the Plugin a warning.

"SignedInNotSupported"

>The signed_in parameter has been deprecated and is not supported on the version of the Maps JavaScript API you are using. This won't prevent the Maps JavaScript API from working, but the behavior of your application may change, if you rely on signed-in features.

>Please review your application and see Signed-in Maps | Google Maps JavaScript API for details about the deprecation.

It is not causing any issues at this time; but we may want to address it (to remove the warning and in case of any future changes which are breaking).

More from Google  on this issue -

https://developers.google.com/maps/documentation/javascript/error-messages#signed-in-not-supported

**Comment by CodyReichert** [comment]
Thanks! Do you remember if this is shown by `[sr_listings]`, `[sr_map_search]`, or both?

If it's only shown by `[sr_listings]` (I think this is the case), I believe it is due to the PHP library we use for Google Maps. That library needs to be updated (in any case) to fix the error.

I don't believe it actually prevents the map from displaying.

**Comment by tylerwiegand** [comment]
The pertinent code is in simply-rets-client.js

`            var url = "https://maps.googleapis.com/maps/api/js?signed_in=true&libraries=drawing&callback=startMap" +
                      "&key=" + key;
`

it should also be async, but no it isn't preventing anything from working.

**Comment by CodyReichert** [comment]
Fixed in #145. I just put a quick patch in that PR instead of opening a new one, but this will be resolved in 2.8.0 when it's released a little later today.
