### ISSUE TITLE
Yoast SEO plugin creating incorrect OpenGraph URLs

### ISSUE THREAD

**Issue by spmiller2** [SimplyRETS/simplyretswp#142]
If you have the Yoast SEO Plugin enabled on your site, it will add lines of MetaData for Facebook, and one of them is 

meta property="og:url" content="http://domain.com/?sr-listings=74285095" 

and this URL is not valid.

The only way to address this is to "Disable facebook open graph meta tags" site-wide
https://kb.yoast.com/kb/custom-open-graph-tags/
In WP dash: Yoast -> Social -> Facebook tab

Some alternative would be nice, such as blocking the bad URLs on SimplyRETS pages or forcing Yoast to use the correct link.

**Comment by spmiller2** [comment]
Client reports that even after they remove Yoast, FB continues to create the URL itself - so Yoast and FB are consistently fabricating the same OG URL.  This is with Yoast off

From https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.jbrhomes.com%2Flistings%2F64515064%2F1402%2BMiller%2BStreet%252C%2BWorthington%252C%2BMN%2B56187%2F%3Fsr_vendor%3Dnorthstar

![image](https://user-images.githubusercontent.com/45745190/65293070-b8ebd880-db0e-11e9-9449-56d7ce47e00e.png)

**Comment by spmiller2** [comment]
Updated the title as we've now see that the Share feature in iOS creates the same URL format.

![10-3-2019 9-29-29 AMa](https://user-images.githubusercontent.com/45745190/66145901-905ce780-e5c0-11e9-904c-f23bc541da62.png)

**Comment by chadkraus** [comment]
Hi all,

Has there been any progress on this issue?

On a page like this:
https://www.jbrhomes.com/listings/80254916/1326+4th+Avenue%2C+Worthington%2C+MN+56187/

The cannonical URL in the meta tags is showing as:
<link rel="canonical" href="https://www.jbrhomes.com/sr-listings/80254916/" />

Is the SimplyRETS plugin simply setting that wrong?  Can the plugin's template files set the canonical URL differently so it matches the true URL?

You can see the results of trying to scrape this page here:
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.jbrhomes.com%2Flistings%2F80254916%2F1326%2B4th%2BAvenue%252C%2BWorthington%252C%2BMN%2B56187%2F

Thanks.

**Comment by CodyReichert** [comment]
I think we have a fix for this in #153. We will pull this in ASAP. I would just like to do a _little_ more testing to make sure we didn't break anything, and then get it released. Thanks for all the info here, and sorry for the delay; I didn't quite understand why this was happening, but after some research I think the fix here will work.

cc @chadkraus

**Comment by chadkraus** [comment]
Looking forward to this!  Any idea of the anticipated update date?


Chad Kraus
Senior Web Developer
Lime Valley Advertising, Inc.
1620 S Riverfront Drive
Mankato, MN  56001
P: 507-345-8500
chad@limevalley.com
