### ISSUE TITLE
Fix various PHP warnings and notices

### ISSUE THREAD

**Issue by CodyReichert** [SimplyRETS/simplyretswp#154]
This is kind of an ongoing thing, but there's a few places throughout the code where we need to fix various warnings and notices generated by PHP. For the most part these are all really easy to fix, and we can use this issue to keep track of them as we find them and as users send them in:

## 1. Listings with no `.remarks`
> Notice: Undefined variable: remarks_markup in /var/www/wp-content/plugins/simply-rets/simply-rets-api-helper.php on line 1201

**Comment by spmiller2** [comment]
Another reported by a user on a property detail page.
![unnamed](https://user-images.githubusercontent.com/45745190/72302492-0987c400-361f-11ea-941e-cb004a1b8230.png)

**Comment by CodyReichert** [comment]
Both of these should be fixed, but please re-open if these or any new ones pop up
