### ISSUE TITLE
incorrect results with exteriorFeatures parameter on sr_listings shortcode

### ISSUE THREAD

**Issue by spmiller2** [SimplyRETS/simplyretswp#163]
The exteriorFeatures parameter on the `sr_listings` shortcode doesn't appear to return results which match the requested parameter.

For example, the results returned using

`[sr_listings exteriorFeatures="tub" type="residential"]`
`[sr_listings exteriorFeatures="pool" type="residential"]`
`[sr_listings exteriorFeatures="deck" type="residential"]`

In a market where those are known to be valid returns the exact same results as using simply `[sr_listings type="residential"]`

Querying on the API does work, so those options do appear to be valid in the data.

"https://api.simplyrets.com/properties?type=residential&exteriorFeatures=tub"

or "https://api.simplyrets.com/properties?type=residential&exteriorFeatures=deck"

produce the expected results.

**Comment by CodyReichert** [comment]
Fixed and released in v2.8.9
