### ISSUE TITLE
`[sr_search_form]` attributes not accepted when passing more than 1 value

### ISSUE THREAD

**Issue by spmiller2** [SimplyRETS/simplyretswp#164]
in `[sr_search_form]`, if you pass more than one attribute parameter, like

> [sr_search_form brokers="1523; 345"]

the values are ignored.  However if you just specify one

>[sr_search_form brokers="1523"]

It works correctly.  

It _appears_ this is similar to what was fixed for other shortcodes in #159

**Comment by CodyReichert** [comment]
This is fixed and released in v2.8.9 for the `brokers` and `agent` parameter.

It's possible there's another parameter somewhere with this same issue, but they all be fixed in #124, so I'll close this one and finish it up there.
