### ISSUE TITLE
Maps: Cannot read property `LatLng` of undefined

### ISSUE THREAD

**Issue by CodyReichert** [SimplyRETS/simplyretswp#169]
> Google maps: Cannot read property `LatLng` of undefined

This error has popped up intermittently a couple of times and needs more information to reproduce and investigate.

This error message is from memory, it might be slightly different.

**Comment by dallendalton** [comment]
I just experience this error as well. Found this issue containing more information and potential fixes:
https://github.com/egeloen/ivory-google-map/issues/296

**Comment by CodyReichert** [comment]
@dallendalton -- Thank you for finding that! I didn't see it when I was looking yesterday, but that's a big help.

I'm working on this right now and we will have a fix up in the plugin ASAP.

**Comment by CodyReichert** [comment]
I was able to get this patched up in our fork of ivory-google-map

The fix for this issue is here: #174. There is a zip file attached to that PR with the patch included, for anyone who wants to help test or needs the fix immediately.

We are testing the changes here internally, and will release as version 2.9.0 as soon as the fix is confirmed.
