### ISSUE TITLE
Suggestion: make it easier to override templates

### ISSUE THREAD

**Issue by daltonrooney** [SimplyRETS/simplyretswp#17]
Many plugins that implement custom post types allow you to override the templates with a custom template in the theme directory. I'm working with a client who wants a custom layout for their property pages and it doesn't look like we'll be able to implement that within the plugin. Any ideas?

**Comment by CodyReichert** [comment]
I believe there was a bug in the initial implementation that was resolved a few months ago. A solution for anyone else who comes across this:

SimplyRETSWP will check for a file named `single-sr-listings.php` in your theme or child-theme. If that's not available, it will use the `page.php` template.

So you can add that file to your theme and customize the template from there. Importantly, all of the inner markup generated by SimplyRETS is still the same. But you can work around that and show the listing detailsanywhere with `the_content()`.

Anyone feel free to comment or re-open if there's any question/issues! Thanks for opening it @daltonrooney, sorry we didn't find that bug earlier!
