### ISSUE TITLE
Results sort - prioritize brokers or agent listings in results

### ISSUE THREAD

**Issue by spmiller2** [SimplyRETS/simplyretswp#172]
Some brokers and agents would prefer their listings return first in any search results.  This could be accomplished by specifying a filter on the `sr_listings` or `sr_search_form` shortcodes using the agentid or officeid

**Comment by CodyReichert** [comment]
My recommendation for doing this would be to use two short-codes on a page:

```
Listings page

[sr_search_form]
[sr_listings agent="my_agent_id" limit="500"]
[sr_listings]
```

By using a high `limit` (500) on the first short-code, you will avoid showing previous/next pagination links at the bottom of the first list. Then it blends in nicely with the one below it.

One caveat would be that the agent's listings would show up in the second list sometimes, but it's still a pretty good solution.

I don't immediately see how this could be done in the plugin alone. Without some sort of API support it would be imperfect in some spots. But the above should work well for most use-cases.

Please re-open if I misunderstood the feature request.
