### ISSUE TITLE
in_array() expects parameter 2 to be array

### ISSUE THREAD

**Issue by emmanuel1982** [SimplyRETS/simplyretswp#173]
Just installed the WP plugin demo and it tells me the following on every page:

Warning: in_array() expects parameter 2 to be array, string given in /srv/users/.../public/wp-content/plugins/simply-rets/simply-rets-api-helper.php on line 571

**Comment by CodyReichert** [comment]
Hey @emmanuel1982 -- thank you for reporting this!

I have a PR up #175 with a fix for this one and a couple of other warnings/notices I saw while testing.

There's a `.zip` file on the #175 page you can use to test the fixes, and we'll have a new official version released shortly.
