### ISSUE TITLE
MLS CDN Image URLs not SSL

### ISSUE THREAD

**Issue by spmiller2** [SimplyRETS/simplyretswp#180]
Is there any way we could provide an option to let the client change MLS image URLs to HTTPS?

It would be up to the client to do as we can't guarantee that an MLS has images available on HTTPS when they don't include them that way on the CDN - but in the case they did, we could allow them to set HTTPS as preferred.

**Comment by CodyReichert** [comment]
Actually... yeah, we could have that as an admin setting. The plugin would be the best place to do it and it seems common enough to warrant providing a solution.

The implementation seems straightforward: Before we set an img tag's `src`, we can look for this setting and look at the image URL to determine if we need to modify it.

**Comment by spmiller2** [comment]
This was added as a feature.  As Cody described, it is an option in Settings.

![image](https://user-images.githubusercontent.com/45745190/144725491-7dca5346-1f18-4556-adce-619b86b421b0.png)
