### ISSUE TITLE
Use 'count=false' query parameter in all queries

### ISSUE THREAD

**Issue by creichert** [SimplyRETS/simplyretswp#19]
**UPDATE:** Moved to #128

**Comment by CodyReichert** [comment]
Just making a note here that this is related to #2. Generally, this is the behavior I'm looking for:

- Have an admin option to enable/disable showing "Total count" on search result pages (see #2)
- If the option is _disabled_, add `count=false` to all API requests.
- If the option is _enabled_, show the total number of results on search pages.
