### ISSUE TITLE
Saving Some Fields Clears Values From Others

### ISSUE THREAD

**Issue by WillPresley** [SimplyRETS/simplyretswp#212]
I noticed this issue when saving the 'Default timezone' value, and the 'Custom disclaimer' field is then cleared out. It seems like some data is not being sent when one of the 'Save Changes' buttons is clicked. A lot of plugins label those buttons 'Save All Changes' and are sure to push all the field values, maybe that could work here too. If I ever have free time again, I can try to look into it and possibly submit a PR, but that won't be anytime soon, unfortunately.

**Comment by WillPresley** [comment]
@CodyReichert @spmiller2 
Is there any chance that this has been fixed in any newer versions of the plugin? I am back on this client's site making some changes, and noticed that other areas are being cleared out when saving things like the Timezone on the Admin Settings page.

**Comment by CodyReichert** [comment]
Hey @WillPresley thanks for following up on this. I was able to reproduce the issue on the latest version. Primarily, it seems like this happens only on the "Custom disclaimer" and "No search results" text field settings. For some reason those are cleared when saving any other fields.

Did you notice any other fields being cleared as well? Just want to make sure I'm not missing anything.

I will dig into this one more today and see if we can get a fix out asap.
