### ISSUE TITLE
Next Link showing when no more records, produces "offset is too high"

### ISSUE THREAD

**Issue by spmiller2** [SimplyRETS/simplyretswp#213]
There may be a logic bug in the "next" link in the plugin. It seems to be showing when there are no more records in the set. If you click it, you get a result saying "offset is too high"

**Comment by joelflint** [comment]
Hey Scott,

Thanks for the thorough response. I took some time off for the holidays, but I'm back and working on this again.
Here is the code I added to `simply-rets-api-helper.php` after line `1355`.

```
/** Check if there should be a prev and/or next button displayed */
parse_str(parse_url($pagination['next'], PHP_URL_QUERY), $next_atts);
if (count($response) < intval($next_atts['limit'])) {
  $next_link = null;
}
```

It's just a simple hack that made my situation work, but hopefully it helps you guys figure out why `$next_link` was populated by:
```
$pag = SrUtils::buildPaginationLinks( $pagination );
```

I believe `$pagination` already came in with a 'next' value, so it's most likely something upstream from `srResidentialResultsGenerator`, but I didn't dig too much. For a live link you can see it here:
https://torreon.com/listings/?sr-listings=sr-search&sr_brokers=RealtyTor

Unfortunately, it seems as though the listings are down to a single page right now, but possibly at a later date they will expand out. I'll try to help as much as possible on this issue.

Thanks!
