### ISSUE TITLE
Plugin generates errors with WP_DEBUG turned on

### ISSUE THREAD

**Issue by daltonrooney** [SimplyRETS/simplyretswp#25]
I see the following errors in WP-Admin when the plugin is activated and WP_DEBUG is turned on:

Notice: Undefined variable: matches in /srv/www/site/htdocs/wp-content/plugins/simply-rets/simply-rets-post-pages.php on line 93

Notice: Undefined variable: matches in /srv/www/site/htdocs/wp-content/plugins/simply-rets/simply-rets-post-pages.php on line 93

Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method SrAdminSettings::add_to_admin_menu() should not be called statically in /srv/www/site/htdocs/wp-includes/plugin.php on line 525

Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method SrAdminSettings::register_admin_settings() should not be called statically in /srv/www/site/htdocs/wp-includes/plugin.php on line 525

Notice: Undefined index: sr-listings in /srv/www/site/htdocs/wp-content/plugins/simply-rets/simply-rets-post-pages.php on line 772

Notice: Undefined index: sr-listings in /srv/www/site/htdocs/wp-content/plugins/simply-rets/simply-rets-post-pages.php on line 775

Notice: Undefined index: sr-listings in /srv/www/site/htdocs/wp-content/plugins/simply-rets/simply-rets-post-pages.php on line 804

**Comment by RobertLeahy** [comment]
I am also experiencing this issue.

**Comment by CodyReichert** [comment]
Hey @daltonrooney - thanks for the report! It looks like those are mostly just ill-formed function calls due to some code that was probably refactored at some point. We should definitely get them cleaned up so that WP_DEBUG is usable and not littered w/ SimplyRETS warnings.

Just to clarify - this isn't causing any issues for you in production with WP_DEBUG turned off, right?

**Comment by daltonrooney** [comment]
Thanks for looking into this! As far as I can tell everything is fine with WP_DEBUG turned off.

**Comment by CodyReichert** [comment]
Howdy -- I know it's late :)

v2.5.0 fixes _all_ of the WP_DEBUG warnings I could find. If anyone spots anymore please open a new issue - closing this one! :+1:
