### ISSUE TITLE
Listings Display Page - No Form Option and Classic Gallery

### ISSUE THREAD

**Issue by sturple** [SimplyRETS/simplyretswp#26]
# Style Issue

If you
- disable contact form lead capture 
- and have Classic Gallery Enabled

You get the 'See more photos |'

**Comment by CodyReichert** [comment]
Hey @sturple - right again. I feel like we may have handled this correctly at one point, but I'm not sure. Should be a simple fix - I'll try and get this one out with the next release as well!

**Comment by CodyReichert** [comment]
I believe this is fixed in the latest version (has been, actually, just forgot to close the issue) - but please reopen if the problem still exists!
