### ISSUE TITLE
On listing Index have multiple dom ID of same value

### ISSUE THREAD

**Issue by sturple** [SimplyRETS/simplyretswp#27]
## Listing Index on h4 title has a span that has id="sr-price" on all listing items.

```html
<h4>8369 West MAJESTY STREET Path #1765
  <span id="sr-price"><i>$9,375,751</i></span>
</h4>
```

https://github.com/SimplyRETS/simplyretswp/blob/master/simply-rets-api-helper.php#L1228

**Comment by CodyReichert** [comment]
Hey @sturple -- good find, thank you for reporting. I'll mark this as bug and hopefully we can get a fix out in the next release.

(We will accept PR's, btw. Obviously not required but wanted to throw it out there).
