### ISSUE TITLE
Update Wordpress Plugin Documentation for [sr_listings sort="price"]

### ISSUE THREAD

**Issue by sturple** [SimplyRETS/simplyretswp#29]
In the Wordpress plugin documentation you have an example for the shortcode ``` [sr_listings sort="price"]``` but  this  gives back Invalid Sort Parameter.
After reading the fine print under this option, it had all the valid options, and price was not one of them, so please remove it from the code example.

**Comment by CodyReichert** [comment]
Thanks for the report! Just fixed this one and it will be up in the documentation shortly.
