### ISSUE TITLE
i got a temp user password  by signup-ing on the site, I can't call ( curl ) any real property ?

### ISSUE THREAD

**Issue by jpca999** [SimplyRETS/simplyretswp#47]
where and how do i hook up  id/credentials to call the api ?

**Comment by CodyReichert** [comment]
You can't call cURL on any real property - that's correct. Mentioned in another issue, but there is about 55 listings in the demo data. Check out the FAQ for more info on that: https://simplyrets.com/faq

When you have the plugin installed, you can enter the demo credentials (or your live credentials, if you have an app) on the `Settings -> SimplyRETS` page from your WP dashboard.
