### ISSUE TITLE
Add parameter to [sr_listings] to show properties listed within so many days

### ISSUE THREAD

**Issue by wesleycole** [SimplyRETS/simplyretswp#52]
I would like to see a way to show products that were listed within so many days. This could be a parameter passed into the `[sr_listings]` shortcode. 

I'm thinking something like `[sr_listings days_on_market="14"]` or something like that.

**Comment by CodyReichert** [comment]
Thanks for the contribution, Wes! The SimplyRETS API does actually have a [`maxdom` query parameter](https://docs.simplyrets.com/api/index.html#!/default/get_properties). so this can be supported in the plugin as well:

> Filter listings by a maximum number of days on market.

Does that parameter sound like it would work for your use-case?
For example, `[sr_listings maxdom="14"]` would show only listings where days on market is less than 14.

**Comment by CodyReichert** [comment]
`maxdom` is supported in the short-codes!

Please re-open if you need anything else here.
