### ISSUE TITLE
Plugin install from .zip fails

### ISSUE THREAD

**Issue by mbghsource** [SimplyRETS/simplyretswp#81]
**I get the following error:**
Warning: require(/var/www/html/wp-content/plugins/simplyretswp-2.4.7/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/simplyretswp-2.4.7/simply-rets.php on line 19

Fatal error: require(): Failed opening required '/var/www/html/wp-content/plugins/simplyretswp-2.4.7/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/simplyretswp-2.4.7/simply-rets.php on line 19

**when I tried the following Installation instruciton**
Installation
Install from .zip file
Download the `.zip` file from the releases page.
In your Wordpress dashboard, go to ‘Plugins’ -> ‘Add New’. Choose ‘Upload a New Plugin’ and upload the `.zip` file.
Activate it through the Plugins -> Installed plugins page of your Wordpress dashboard.

**I could get it to work by**
extracting the .zip file
running 'composer install' inside the extracted directory, which created the vendor/ artifacts
re-creating the zip file
updating the instructions would be useful for newbies like me.

**Comment by CodyReichert** [comment]
Ah, thank you for the report @mbghsource - will get a fix up ASAP.

One last thing -- where did you download the .zip file from? It might that, the zip file uploaded to GitHub doesn't have the vendor directory whereas the zip file on WordPress.org does (I think).

Thanks again - let me know!

**Comment by mbghsource** [comment]
https://github.com/SimplyRETS/simplyretswp/archive/v2.4.7.zip

**Comment by CodyReichert** [comment]
Hey @mbghsource - just pushed updates to the README with fixed installation instructions: https://github.com/SimplyRETS/simplyretswp#installation

The `vendor/` artifacts _are_ included when downloading the zip file from WordPress, so I updated the instructions to download it from there instead of GitHub (who doesn't include the vendor artifacts), but I also added instructions about composer install for anyone who does download the GitHub zip file.

Thanks again for the report - sorry for the troubles!

**Comment by mbghsource** [comment]
Hey @CodyReichert 
Looking at your update, I see - "run composer install in the unzipped directly". Did you mean "unzipped directory" ?

**Comment by CodyReichert** [comment]
Ah thanks for reviewing that @mbghsource - you're right, just a typo. Pushed a fix (for the formatting also). Thanks again - let me know if you hit anything else!
