### ISSUE TITLE
Add SSL to demo site

### ISSUE THREAD

**Issue by CodyReichert** [SimplyRETS/simplyretswp#84]
Support HTTPS on: http://wordpress-demo.simplyrets.com

**Comment by creichert** [comment]
Ah, right. Either of us can go add the wildcard cert to AWS ACM. I believe you should be able to apply it to that lighthouse instance, but I'm not 100% sure.

**Comment by CodyReichert** [comment]
This is done. For more information:

AWS ACM doesn't integrate directly with LightSail, so it's not as simple as some of the other domains. As of right now, we are just utilizing LightSail's default toolset to support [SSL through LetsEncrypt](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-using-lets-encrypt-certificates-with-wordpress).

Because this SSL cert was installed using "`manual`" authentication, it needs to be manually renewed every 90 days. In the future, it looks like we can use [another `certbot` authentication plugin](https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins) that will allow us to set up auto-renewal.
