### ISSUE TITLE
Pretty Permalinks sometimes don't work

### ISSUE THREAD

**Issue by CodyReichert** [SimplyRETS/simplyretswp#9]
Sometimes pretty permalinks don't work on listing details pages. This issue needs more info and hasn't been pin-pointed to anything yet.
## Problem

When using `pretty permalinks` from the plugin, sometimes single listing pages don't load the listing from the API correctly. It seems to be because WP thinks it is using 'default' permalinks, but the plugin is set to 'pretty'.
## Workaround

1) Set your WordPress permalinks to 'Default'
2) Set your SimplyRETS Permalinks to 'Default' (query string)
3) Set your WordPress permalinks back to whatever you want (eg, `post`)
4) Set your SimplyRETS Permalink settings back to whatever you want (eg, `pretty`)

**Comment by creichert** [comment]
It would be nice to have an exact steps to reproduce, if possible.
